version: '3.8'

services:
  app:
    build: .
    ports:
      - "7152"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production  
    depends_on:
      - db  
    networks:
      - backend

  nginx:
    image: nginx
    ports:
      - "8080:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - app  
    command: [nginx, '-g', 'daemon off;']  
    networks:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql 
    networks:
      - backend

networks:
  backend: